### ISSUE TITLE
Support for Raven 4

### ISSUE THREAD

**Issue by JudahGabriel** [ar0311/RavenDB.DependencyInjection#1]
Hi,

I've got a [similar repo RavenDB.DependencyInjection](https://github.com/JudahGabriel/RavenDB.DependencyInjection) that supports RavenDB 4. **Would you accept a PR for this?** 

Alternately, if you're no longer maintaining this repo, could you transfer ownership of the RavenDB.DependencyInjection NuGet package to me?

**Comment by JudahGabriel** [comment]
@ar0311 bump - would you accept a PR to upgrade to Raven 4? Alternately, if you're not maintaining this repo anymore, I'd be glad to inherit this project.

**Comment by JudahGabriel** [comment]
I haven't heard from you, so I'm assuming this project is no longer maintained. Folks reading this, you can use [RavenDB.AspNetCore.DependencyInjection](https://github.com/JudahGabriel/RavenDB.DependencyInjection) as an alternative that works with the latest RavenDB and AspNetCore.

**Comment by ar0311** [comment]
Apologies Judah, happy for you to take over, will take this repo down shortly.

**Comment by JudahGabriel** [comment]
Thanks! Go ahead and assign me this repo, and grant me access to the NuGet package. Thanks!

**Comment by ar0311** [comment]
Done.

**Comment by JudahGabriel** [comment]
Thank you! I appreciate it. I'll migrate this repo to the latest Raven and update Nuget accordingly. Thanks for your willingness to help.
